const state = {
  activeButton: document.querySelector('#NPB-01'),
  company: IS_Attr_COMPANY_NAME.value,
  lpr: IS_Attr_contactname.value,
  status: IS_Attr_contactstate.value,
  branch: IS_Attr_Heading.value,
  comment: IS_Attr_comment.value,
  address: IS_Attr_Address.value,
  lkLink: IS_Attr_Link_to_personal_account.value,
  q1: IS_Attr_Q1.value,
  q2: IS_Attr_Q2.value,
  q3: IS_Attr_Q3.value,
  q4: IS_Attr_Q4.value,
  q5: IS_Attr_Q5.value,
  //  phone: IS_Attr_contact_phone.value,
  phone: IS_Attr_IS_Attr_Contact_Number1.value,
  jobTitle: IS_Attr_contact_position.value,
  email: IS_Attr_contact_email.value,
  lossReason: IS_Attr_loss_reason_id.value,
  kpDate: IS_Attr_presentation_date.value,
  firstCallDate: IS_Attr_call_date.value,
  price: IS_Attr_budget.value,
  period: IS_Attr_distribution_period.value,
  login: IS_Attr_login.value,
  //  order: '1-TDYH0000',
  expectedPayDate: IS_Attr_pay_date.value,
  trxSMVP: IS_Attr_SMVP_transaction.value,
  payDate: IS_Attr_Pay_date.value,
  flaytId: IS_Attr_id_flight.value,
  sentInvoiceFlag: IS_Attr_tag_sent_invoice.value,
  chosenProduct: IS_Attr_Chosen_product.value
}